POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Edy",
    "number": "123456789"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "987654321"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": ""
}